---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - topo.winlab.nycu
  resources:
  - vxlanfabrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topo.winlab.nycu
  resources:
  - vxlanfabrics/finalizers
  verbs:
  - update
- apiGroups:
  - topo.winlab.nycu
  resources:
  - vxlanfabrics/status
  verbs:
  - get
  - patch
  - update
