apiVersion: topo.winlab.nycu/v1alpha1
kind: VxlanFabric
metadata:
  name: vxlanfabric-sample-2
spec:
  # TODO(user): Add fields here
  # TODO: add new field for new feature
  nodeList:
    - endpoint: "192.168.56.102:30188"
      interface: "banscore"
      outgoing: "enp0s9"
    - endpoint: "192.168.56.103:30188"
      interface: "bansaccess"
      outgoing: "enp0s9"
  slice:
    - sd: "112233"
      # SHOULD be vxlan bridge ip
      src: "192.168.3.102"
      dst: "192.168.3.103"
      rateLimit: 400
  #rateLimit: 800
  #sliceSD: "010203"
